# -*- coding: utf-8 -*-
"""YOLO11_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPvZRdUElkubAzYW-AzC6jyA3788z9W2
"""

!pip install ultralytics -q

import ultralytics
ultralytics.checks()

from IPython.display import Image

Image('/content/bus.jpg')

from google.colab import drive
drive.mount('/content/drive')

! yolo task=segment mode=predict model=yolo11n-seg.pt source='bus.jpg'

Image('/content/runs/segment/predict/bus.jpg')

! yolo task=segment mode=predict model=yolo11s-seg.pt source='bus.jpg'

Image('/content/runs/segment/predict2/bus.jpg')

