# -*- coding: utf-8 -*-
"""YOLO11_Object_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9zD2jjEji0dRj4to3AG0xR74NmDALDm
"""

!pip install ultralytics -q

import ultralytics
ultralytics.checks()

from IPython.display import Image

Image('/content/bus.jpg')

from google.colab import drive
drive.mount('/content/drive')

! yolo task=detect mode=predict model=yolo11m.pt source='bus.jpg'

Image('/content/runs/detect/predict/bus.jpg')

! yolo task=detect mode=predict model=yolo11l.pt source='bus.jpg'

Image('/content/runs/detect/predict2/bus.jpg')

